### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by Idealyinfamous** [Idealyinfamous/super-brain-project#7]
Error suspected on Line 79 to 89. Below is the error it keeps running in the DOM without end. 

To replicate error: 

1. Go to git checkout to frontend branch
2. open "Go live" server in VScode
3. Open DOM in browser 
4. Click on Console tab at top of DOM
5. click " START" button and watch the errors fly! They should looking something like this:

```

jquery.min.js:2 Uncaught TypeError: w.easing[this.easing] is not a function
    at init.run (jquery.min.js:2:55877)
    at u (jquery.min.js:2:59193)
    at w.fx.tick (jquery.min.js:2:62643)
    at at (jquery.min.js:2:56980)
```

**Comment by Idealyinfamous** [comment]
Resolved by Calico
